### ISSUE TITLE
request support native dds format

### ISSUE THREAD

**Issue by fingerx** [unity3d-jp/StreamingImageSequence#69]
DDS can be very fast. Also, hopefully it can be done externally to read the dds file directly, using the C++ plugin. Hopefully this is all multi-threaded, these are helpful for reading a lot of sequence frames.

**Comment by sindharta** [comment]
Because we want to able to use a lot of memory for StreamingImageSequence, we made our current design to load the images on CPU memory (and yes, we use multithreading).
Thus, I don't think there is a lot of benefit in using DDS for loading images on CPU, that is:
- the file size might be bigger
- the quality might be worse

Plus, dds is directx only.

**Comment by fingerx** [comment]
Thank you for your reply.

**Comment by fingerx** [comment]
It's better than before, but still has the same problem, it doesn't work in unity. Use the material I mentioned before. If you can provide me with your email address, I can send you the test material in the next few days. You can try.
